### ISSUE TITLE
Why Thread.currentThread().join() ?

### ISSUE THREAD

**Issue by style-x7** [esanchezros/quickfixj-spring-boot-starter-examples#14]
Hi there,

Some of the examples are having this line of code, what is it needed? 

When I deploy war file of the examples to a shared container server, this is holding up resources from the other war files..

**Comment by esanchezros** [comment]
Hi @style-x7,

Thanks for bring this up. The `Thread.currentThread().join()` was part of the original examples as the starter was run as a `CommandLineRunner` Spring Boot app. As the web context is now available via the actuator, the starter runs now as a webapp, hence the line is obsolete.

I have updated the examples and removed unnecessary code. https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/pull/15

Let me know if you have any questions.
Thanks
Ed
