### ISSUE TITLE
Adding version to poms for logbok

### ISSUE THREAD

**Issue by javaspeak** [esanchezros/quickfixj-spring-boot-starter-examples#17]
I have:

java --version
java 16.0.1 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

mvn install failed with:

[java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment](https://stackoverflow.com/questions/66801256/java-lang-illegalaccesserror-class-lombok-javac-apt-lombokprocessor-cannot-acce)

To fix it I added the version to the poms which had logbok in them:

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.22</version>
        </dependency>

Seems like JDK 16 is particular about the version of lombok

Thanks for the examples

**Comment by esanchezros** [comment]
Hi, thanks for reporting. Feel free to create a PR for this bug. I probably need to add pipelines for Java 8, 11 and 16/17 to verify the build with different versions

**Comment by jgarciasm** [comment]
This is also the case with JDK 17. The same solution

**Comment by esanchezros** [comment]
Thanks for reporting @jgarciasm. I'm busy at work at the moment but I'll try fixing this soon. Otherwise feel free to submit a PR if you prefer,

**Comment by press0** [comment]
> mvn clean install

BUILD SUCCESS

> java -jar simple-server/target/simple-server.jar

no main manifest attribute, in simple-server/target/simple-server.jar

**Comment by esanchezros** [comment]
Fixed
