### ISSUE TITLE
Can't start simple-server-with-database 

### ISSUE THREAD

**Issue by PhanNN** [esanchezros/quickfixj-spring-boot-starter-examples#18]
Hello,

After run `mvn clean install`, I import simple-server-with-database into Eclipse IDE and try to start this project, but the application failed to start because of 
`A configuration error has been detected in the QuickFIX/J settings provided: org.logicalcobwebs.proxool.ProxoolDataSource`
Did you face this problem? 

Thank you

P/s: I try to add proxool, common-logging into pom.xml, but nothing happened!!!

**Comment by esanchezros** [comment]
Hi @PhanNN ,

Thanks for reporting this issue. QuickFixJ uses Proxool as the default DataSource (needed by JDBC store and log for connection pooling). The service should set a different DataSource it in the jdbc factory explicitly.

I'll push a fix for the issue shortly.

Thanks

**Comment by PhanNN** [comment]
@Bean
	public LogFactory serverLogFactory(final SessionSettings serverSessionSettings,
			final DataSource dataSource) {
		final JdbcLogFactory jdbcLogFactory = new JdbcLogFactory(serverSessionSettings);
		jdbcLogFactory.setDataSource(dataSource);
		return jdbcLogFactory;
	}

	@Bean
	public MessageStoreFactory serverMessageStoreFactory(
			final SessionSettings serverSessionSettings, final DataSource dataSource) {
		final JdbcStoreFactory jdbcStoreFactory = new JdbcStoreFactory(serverSessionSettings);
		jdbcStoreFactory.setDataSource(dataSource);
		return jdbcStoreFactory;
	}


Fixed by using BasicDataSource from DbConfiguration :D

**Comment by esanchezros** [comment]
Thanks, that's exactly the change I pushed yesterday. Many thanks @PhanNN
