### ISSUE TITLE
Example using quickfixj.client.configString

### ISSUE THREAD

**Issue by ggershaw** [esanchezros/quickfixj-spring-boot-starter-examples#19]
Hi,

I've tried several approaches to add the default/session level properties as a value to the above mentioned property. When I attempt to run in the latest Boot 2.x version, boot dies with an error code and no explanation as to what occurred. Maybe an exception is being swallowed?

I've looked through your examples repo and found all the examples use a .cfg file to hold the default and session level settings. Would you please create an example using configString.

**Comment by esanchezros** [comment]
https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/tree/master/simple-client-and-server-config-string

**Comment by ggershaw** [comment]
Hello,

Almost to New Years!! I downgraded to the latest 2.x boot. I see FIX messages in the logs of both the client and the server. This is great. I am hitting what I believe is the final problem. For some reason, the server is picking up the client's cfg file. I have looked at all your examples and believe I have made a correct yml file. I've forced pushed to the branch. If you have time, can you try and run BootifiedServer. You'll see in the log output that its picking up the client.cfg

[main] INFO org.gershaw.quickfixj.springboot.server.BootifiedServer - Starting BootifiedServer using Java 19.0.1 on DESKTOP-NNERO46 with PID 3788 (C:\Users\ggers\IdeaProjects\Examples\spring-boot-starter\target\classes started by ggers in C:\Users\ggers\IdeaProjects\Examples)
[main] INFO org.gershaw.quickfixj.springboot.server.BootifiedServer - No active profile set, falling back to 1 default profile: "default"
[main] INFO io.allune.quickfixj.spring.boot.starter.connection.SessionSettingsLocator - Loading settings from 'classpath:/quickfixj-client.cfg'

Thanks for your time and help! When I publish this example on LinkedIn would you be okay with me giving you a shout out. I would also like to point to your repo on my readme with your permission

Best
________________________________

**Comment by esanchezros** [comment]
Hi,

Seems like a copy-paste error. In `BootifiedServer` you're loading `BootifiedClient` :smiley: Once changed it loads `quickfixj-server.cfg`
