### ISSUE TITLE
MANIFEST.MF 

### ISSUE THREAD

**Issue by press0** [esanchezros/quickfixj-spring-boot-starter-examples#21]
> mvn clean install

BUILD SUCCESS

> java -jar simple-server/target/simple-server.jar

no main manifest attribute, in simple-server/target/simple-server.jar

maybe https://www.baeldung.com/spring-boot-fix-the-no-main-manifest-attribute

**Comment by esanchezros** [comment]
Hi @press0,

Thanks for reporting, I'll try to fix it this weekend.

**Comment by esanchezros** [comment]
Fixed
