### ISSUE TITLE
Question about the implementation

### ISSUE THREAD

**Issue by apupneja** [esanchezros/quickfixj-spring-boot-starter-examples#24]
Hi, 

I was going through this link(https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/tree/master/simple-server-spring-3/src/main/java/io/allune/quickfixj/spring/boot/starter/examples/server). This creates a Application adapter which is responsible for dealing with the messages that are created by the client. Is that correct?

So, in case of this example, I try to setup a client too, by just adding `@EnableQuickFixJClient` to the application. This would mean that a client is created that would be automatically. So, now the server would be using the ServerApplicationAdapter to deal with the messages. Is this the case? I'm asking this because according to this, only the incoming message should be logged, but I also see an outgoing message. How is that created? I tried going through the source code but not sure about how this might be happening.

Any explanation is appreciated.

**Comment by esanchezros** [comment]
Hi @apupneja 

So this is a spring boot starter for the QuickFix/J library. The starter takes care of creating the common components involved in starting an Initiator (usually referred to as client side) or an Acceptor (usually referred to as server side). If you are trying to connect to an Exchange or Acceptor, you should act as the Initiator in the connection. 

The QuickFix/J library provides with an interface called `Application` that allows the Initiator to be notified of events that occur on the connection with the Acceptor. The same interface is used if you are implementing an Acceptor.

https://www.quickfixj.org/usermanual/2.3.0/usage/application.html

You can start the other side yourself by running the client https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/tree/master/simple-client-spring-3/src/main/java/io/allune/quickfixj/spring/boot/starter/examples/client along with the server you sent in the question and see both running at the same time.

**Comment by apupneja** [comment]
Thank you for the detailed explanation @esanchezros . So, what happens when both the @EnableQuickFixJClient and @EnableQuickFixJServer are given to the application class? (Something like the simple client server example)

What part of the source code allows them to communicate indefinitely? I'm assuming that the default application adapter keeps sending the message back and forth.

But why does the same happen when I return an implementation of the Application which just logs everything? What has allowed the server to respond in that case?

If possible, can you please take reference from the original starter code.

**Comment by esanchezros** [comment]
@apupneja, when you have both `@EnableQuickFixJClient` and `@EnableQuickFixJServer` in the application you will have 2 independent applications, one for the Initiator and one for the Acceptor. For example, an acceptor (@EnableQuickFixJServer) talking with a third party Initiator, and an Initiator (@EnableQuickFixJClient) talking with a third party acceptor. But the server-and-client example does not connect the Initiator with the Acceptor or vice versa. 

This kind of setup is useful when you have things like a protocol adapter (i.e. FIX4.2 -> FIX5.0SP2 and FIX5.0SP2 -> FIX4.2) where your Acceptor only talks FIX5.0SP2 but a client only talks FIX4.2

`Third Party 4.2 Initiator ----> your 4.2 Acceptor (EnableQuickFixJServer) --> Mapping logic in your app to 5.0SP2 ----> Send to 5.0SP2 Acceptor`

`5.0SP2 Acceptor ----> your 5.0SP2 Initiator (EnableQuickFixJClient) --> Mapping logic in your app to 4.2 ----> Send to Third Party 4.2 Initiator`

An initiator's Application has methods like `toApp` (This is a callback for application messages that you are being sent to a counterparty or Acceptor) and `fromApp` (This callback is for messages received from the counterparty or Acceptor). What you see are these messages.

**Comment by apupneja** [comment]
I really appreciate the explanations. One last thing that I'm a little confused about is that in the case of example applications, what part of the code is acting as the third party initiator and sending the stream of message?

I ask this because, even before I used any endpoints, there was a stream of messages. 

Again, sorry for the number of questions I've asked.

**Comment by esanchezros** [comment]
The third party initiator or acceptor isn't configured. The example just illustrates that the spring boot starter is capable of creating an Initiator and Acceptor in the same app.

I was wrong in my last message. The client and server talk to each other. The stream of messages that you see are probably the logon request, logon response and heartbeats between the two. But you can hook the Initiator in the example with a different Acceptor, and the Acceptor in the example with a different Initiator

**Comment by apupneja** [comment]
Right, those were the heartbeat messages. Thank You.
