### ISSUE TITLE
Add examples for sending messages between client and server

### ISSUE THREAD

**Issue by esanchezros** [esanchezros/quickfixj-spring-boot-starter-examples#5]

**Comment by ViniciusMRosa** [comment]
Hi @esanchezros, i'm trying to understand how to send a message to server but i can't get a clue.
Do I have to use Session.sendToTarget or `ApplicationAdapter` class is suposed to do the job?
I would submit a PR with some examples as soon as I can figure it out.
Regards, and thank you so much for the starter.

**Comment by esanchezros** [comment]
Hi @ViniciusMRosa,

I'm working on creating better examples and extending the starter with the means to send messages. 

The ApplicationAdapter is just the default implementation of the Application interface which is the primary interface for processing session messages. These messages can be administrative (fromAdmin, toAdmin), session (onCreate, onLogon, onLogout) and application (fromApp, toApp). You can send messages to the Initiator or Acceptor if a session is started, using Session.send if you have the session object, or Session.sendToTarget if you know the sender and target (internally quickfixj does a lookup of the session).

Please feel free to add examples or extend the existing ones, all the help is welcome.

Regards,
Eduardo

**Comment by ViniciusMRosa** [comment]
Thanks, Eduardo!
As soon as I have a working code I post some examples.

**Comment by sandeepsuvit** [comment]
I was trying to use a service class to send the message between client and service, unfortunately i couldn't figure out how to get the session id to use within ```Session.sendToTarget(newOrderSingle, sessionId);```. Any pointers on this?

**Comment by esanchezros** [comment]
Hi Sandeep,

You can do a `Session session = Session.lookupSession(sessionID)` and then `session.send(newOrderSingle)`.

BTW, I'm currently working on a `QuickFixJTemplate` that will allow sending messages, looking up the session if necessary. I will try to release this new feature in the coming weeks.

https://github.com/esanchezros/quickfixj-spring-boot-starter/tree/quickfixj-template

Regards,
Eduardo

**Comment by sandeepsuvit** [comment]
Tried something like this and i am able to ge the message on the acceptor end, but not sure if i am doing it correctly. Note that this would only work if we use the listener methodology wherein spring initiates the Application class internally.

```java
@Slf4j
@Service
public class TradeServiceImpl implements TradeService {
	
	@Autowired
	SocketInitiator socketInitiator;
	
	@Override
	public void performDummyTrade() {
		log.info("Entering method performDummyTrande in class {}", this.getClass().getName());
		// In real world this won't be a hard coded value rather than a sequence.
		ClOrdID orderId = new ClOrdID("1");

		// to be executed on the exchange
		HandlInst instruction = new HandlInst(HandlInst.AUTOMATED_EXECUTION_ORDER_PRIVATE_NO_BROKER_INTERVENTION);
		
		// Since its FX currency pair name
		Symbol mainCurrency = new Symbol("USD");

		// Which side buy, sell
		Side side = new Side(Side.BUY);

		// Time of transaction
		TransactTime transactionTime = new TransactTime();

		// Type of our order, here we are assuming this is being executed on the
		// exchange
		OrdType orderType = new OrdType(OrdType.FOREX_MARKET);

		NewOrderSingle newOrderSingle = new NewOrderSingle(orderId, instruction, mainCurrency, side, transactionTime,
				orderType);

		// Quantity
		newOrderSingle.set(new OrderQty(1));
		try {
                        // Get the session
			SessionID sessionId = socketInitiator.getSessions().get(0);
			
			Session.sendToTarget(newOrderSingle, sessionId);
			log.info("Exiting method performDummyTrande in class {}", this.getClass().getName());
		} catch (SessionNotFound e) {
			e.printStackTrace();
		}
	}
}
```

**Comment by esanchezros** [comment]
Hi Sandeep.

The quickfixj sping starter will create an `Application` bean if there isn't one in the context. By default, it uses event publishing to broadcast the messages. You can provide your own `Application` bean if you want to customize how you handle and broadcast your messages.

There is an example in `simple-client` in the example project that illustrates this:

https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/tree/examples-enhancements/simple-client

**Comment by robertfernanV** [comment]
> Hi Sandeep.
> 
> The quickfixj sping starter will create an `Application` bean if there isn't one in the context. By default, it uses event publishing to broadcast the messages. You can provide your own `Application` bean if you want to customize how you handle and broadcast your messages.
> 
> There is an example in `simple-client` in the example project that illustrates this:
> 
> https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/tree/examples-enhancements/simple-client

Hi @esanchezros  the link of example dont exist, where is? thanks

**Comment by esanchezros** [comment]
Hi Roberto. 
Try this
https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/tree/master/simple-client
That was a link to a branch that got merged into master a while back

**Comment by robertfernanV** [comment]
> Hi Roberto.  Try this https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/tree/master/simple-client That was a link to a branch that got merged into master a while back  Sent from Yahoo Mail on Android On Mon, 2 Mar 2020 at 13:54, Roberto Fernandez<notifications@github.com> wrote: Hi Sandeep. The quickfixj sping starter will create an Application bean if there isn't one in the context. By default, it uses event publishing to broadcast the messages. You can provide your own Application bean if you want to customize how you handle and broadcast your messages. There is an example in simple-client in the example project that illustrates this: https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/tree/examples-enhancements/simple-client Hi @esanchezros the link of example dont exist, where is? thanks — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

thanks for the reply, i dont explain well, my question is: how to send messages to fix with the client?, because when executing that code it connects and everything is perfect but there is no example of how to use that connection
Thanks

**Comment by esanchezros** [comment]
Have a look at issue #4. There is an example there on how to use the client initiator to retrieve a session and send a message.

You can also autowire the client `QuickFixJTemplate` (`clientQuickFixJTemplate`) and send a message to a SessionID. Here is an example using the `serverQuickFixJTemplate`:

https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/blob/master/simple-server-sender/src/main/java/io/allune/quickfixj/spring/boot/starter/examples/sender/SenderController.java

**Comment by robertfernanV** [comment]
@esanchezros thanks for the answer, when I try I give you news, i have another question, why i clone simple client proyect when add other controller give me error for return stirng? for exmaple: 

![image](https://user-images.githubusercontent.com/13409353/75880653-7425d680-5dfc-11ea-8240-b0c76c42237b.png)

do you have the same response?
Thanks
